#!/bin/bash
# Copyright(C) 2013 Mark Clarkson <mark.clarkson@smorg.co.uk>
#
#    This software is provided under the terms of the GNU
#    General Public License (GPL), as published at: 
#    http://www.gnu.org/licenses/gpl.html .
#
# File:     check_initramfs
# Date:     20 Nov 2015
# Version:  0.10
# Modified: xx Jun 2015 by Mark Clarkson <mark.clarkson@smorg.co.uk>
#             Sample
#
# Purpose:  Check initramfs in /boot is not truncated.
#
# Notes:
#


# ---------------------------------------------------------------------------
# DEFAULTS (Change as necessary)
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# DON'T TOUCH ANYTHING BELOW
# ---------------------------------------------------------------------------

ME="$0"
CMDLINE="$@"
TRUE=1
FALSE=0
VERSION="0.10"
OK=0
WARN=1
CRIT=2
UNKN=3

USESUDO=0
WITHPERF=0
SUDO="sudo "

declare -i CORRUPT=0 USESUDO=0 WITHPERF=0
declare -i CRITLVL=90 WARNLVL=50

# ---------------------------------------------------------------------------
main()
# ---------------------------------------------------------------------------
{
    local retval txt msg

    retval=$OK

    parse_options "$@"

    sanity_checks

    # Fill in the stats variables 
    do_check

    txt="OK:"
    msg="Initramfs files are good."

    [[ $CORRUPT -ge 1 ]] && {
        filesare="files are"
        [[ $CORRUPT -eq 1 ]] && filesare="file is"
        txt="CRITICAL:"
        msg="$CORRUPT initramfs $filesare bad. System may not survive a reboot!"
        msg+=" Run 'gzip -t /boot/initram*' on the server."
        retval=$CRIT
    }

    out="$txt $msg"

    [[ $WITHPERF -eq 1 ]] && {
        out="$out | 'Corrupt Initramfs Images'=$CORRUPT;1;1;0;20"
    }

    echo "$out"

    exit $retval
}

# ---------------------------------------------------------------------------
sanity_checks()
# ---------------------------------------------------------------------------
{
    for binary in gzip; do
        if ! which $binary >& /dev/null; then
            echo "$UNKNOWN: $binary binary not found in path. Aborting."
            exit $UNKN
        fi
    done

}

# ----------------------------------------------------------------------------
usage()
# ----------------------------------------------------------------------------
{
    echo
    echo "`basename $ME` - Alert if Slab usage is high."
    echo
    echo "Usage: `basename $ME` [options]"
    echo
    echo " -p      :  Add performance data output for graphing."
    echo " -w NUM  :  Warning alert if Slab memory exceeds NUM % of RAM."
    echo "            Default is 50."
    echo " -c NUM  :  Critical alert if Slab memory exceeds NUM % of RAM."
    echo "            Default is 90."
    echo " -h      :  Display this help text."
    echo
    echo "Example:"
    echo
    echo "  Check that Slab does not exceed 50% or 90% of RAM"
    echo
    echo "    ./`basename $ME`"
    echo
}

# ---------------------------------------------------------------------------
do_check()
# ---------------------------------------------------------------------------
{
    local -i found=0
    local i

    for i in /boot/initramfs*; do
        [[ ! -r "$i" ]] && {
            echo "Cannot read '$i'. Aborting"
            exit $UNKN
        }
        gzip -t "$i" 2>/dev/null
        [[ $? -ne 0 ]] && CORRUPT+=1
    done
}

# ----------------------------------------------------------------------------
parse_options()
# ----------------------------------------------------------------------------
# Purpose:      Parse program options and set globals.
# Arguments:    None
# Returns:      Nothing
{
    set -- "$@"
    while true
    do
        case $1 in
            #-s) USESUDO=1
            #;;
            -p) WITHPERF=1
            ;;
            -h) usage
                exit 0
            ;;
            ?*) usage
                echo "ERROR: Syntax error, '$2'."
                exit 4
            ;;
        esac
        shift 1 || break
    done

    [[ $USESUDO -ne 1 ]] && SUDO=
}

main "$@"

exit 0

